"""Real catalog data extracted from ContentView.swift (verbatim)."""

GHOSTS = [
    {"key": 'poltergeist', "name": '👻 Poltergeist', "emoji": '👻', "rarity": 'common', "points": (10, 20)},
    {"key": 'specter', "name": '👻 Specter', "emoji": '👻', "rarity": 'common', "points": (10, 20)},
    {"key": 'phantom', "name": '👻 Phantom', "emoji": '👻', "rarity": 'common', "points": (10, 20)},
    {"key": 'wraith', "name": '👻 Wraith', "emoji": '👻', "rarity": 'common', "points": (10, 20)},
    {"key": 'banshee', "name": '👻 Banshee', "emoji": 'Scream Attack - Stuns all ghosts', "rarity": 'common', "points": (10, 20)},
    {"key": 'ghoul', "name": '🧟 Ghoul', "emoji": '🧟', "rarity": 'common', "points": (10, 20)},
    {"key": 'zombie', "name": '🧟 Zombie', "emoji": '🧟', "rarity": 'common', "points": (10, 20)},
    {"key": 'mummy', "name": '🧟 Mummy', "emoji": '🧟', "rarity": 'common', "points": (10, 20)},
    {"key": 'vampire', "name": '🧛 Vampire', "emoji": '🧛', "rarity": 'uncommon', "points": (25, 40)},
    {"key": 'werewolf', "name": '🐺 Werewolf', "emoji": '🐺', "rarity": 'uncommon', "points": (25, 40)},
    {"key": 'witch', "name": '🧙 Witch', "emoji": '🧙', "rarity": 'uncommon', "points": (25, 40)},
    {"key": 'ghostKnight', "name": '⚔️ Ghost Knight', "emoji": '⚔️', "rarity": 'uncommon', "points": (25, 40)},
    {"key": 'shadowDemon', "name": '🌑 Shadow Demon', "emoji": '🌑', "rarity": 'uncommon', "points": (25, 40)},
    {"key": 'demonLord', "name": '👿 Demon Lord', "emoji": 'Inferno - Burns all enemies', "rarity": 'rare', "points": (50, 75)},
    {"key": 'ancientSpirit', "name": '🏛️ Ancient Spirit', "emoji": '🏛️', "rarity": 'rare', "points": (50, 75)},
    {"key": 'dragonGhost', "name": '🐉 Dragon Ghost', "emoji": '🐉', "rarity": 'rare', "points": (50, 75)},
    {"key": 'necromancer', "name": '💀 Necromancer', "emoji": '💀', "rarity": 'rare', "points": (50, 75)},
    {"key": 'lichKing', "name": '👑 Lich King', "emoji": 'Raise Dead - Revives fallen ghosts', "rarity": 'epic', "points": (100, 150)},
    {"key": 'voidBeast', "name": '🌀 Void Beast', "emoji": '🌀', "rarity": 'epic', "points": (100, 150)},
    {"key": 'timeWraith', "name": '⏳ Time Wraith', "emoji": 'Time Slow - Slows all movement', "rarity": 'epic', "points": (100, 150)},
    {"key": 'chaosDemon', "name": '🔥 Chaos Demon', "emoji": '🔥', "rarity": 'epic', "points": (100, 150)},
    {"key": 'halloweenKing', "name": '🎃 Halloween King', "emoji": '🎃', "rarity": 'legendary', "points": (300, 500)},
    {"key": 'pumpkinLord', "name": '🎃 Pumpkin Lord', "emoji": '🎃', "rarity": 'legendary', "points": (300, 500)},
    {"key": 'nightmare', "name": '🌙 Nightmare', "emoji": 'Fear Aura - Reduces enemy stats', "rarity": 'legendary', "points": (300, 500)},
    {"key": 'voidEntity', "name": '🌌 Void Entity', "emoji": '🌌', "rarity": 'legendary', "points": (300, 500)},
]

CANDIES = [
    {"key": 'chocolate', "name": '🍫 Chocolate', "points": 3},
    {"key": 'lollipop', "name": '🍭 Lollipop', "points": 3},
    {"key": 'gummi', "name": '🐻 Gummi', "points": 3},
    {"key": 'candyCorn', "name": '🌽 Candy Corn', "points": 2},
    {"key": 'licorice', "name": '🖤 Licorice', "points": 2},
    {"key": 'jawbreaker', "name": '🔴 Jawbreaker', "points": 2},
    {"key": 'taffy', "name": '🍬 Taffy', "points": 2},
    {"key": 'peppermint', "name": '🍬 Peppermint', "points": 2},
    {"key": 'truffle', "name": '🍫 Truffle', "points": 5},
    {"key": 'caramel', "name": '🍬 Caramel', "points": 5},
    {"key": 'fudge', "name": '🍫 Fudge', "points": 5},
    {"key": 'toffee', "name": '🍬 Toffee', "points": 5},
    {"key": 'goldenCandy', "name": '⭐ Golden Candy', "points": 15},
    {"key": 'magicalCandy', "name": '✨ Magical Candy', "points": 20},
    {"key": 'rainbowCandy', "name": '🌈 Rainbow Candy', "points": 25},
    {"key": 'candycornKing', "name": '👑 Candy Corn King', "points": 50},
    {"key": 'chocolateDragon', "name": '🐉 Chocolate Dragon', "points": 60},
    {"key": 'lollipopTower', "name": '🗼 Lollipop Tower', "points": 70},
]

MINIGAMES = [
    ('memoryMatch', '🧠 Memory Match'),
    ('pumpkinSmash', '🎃 Pumpkin Smash'),
    ('ghostRace', '👻 Ghost Race'),
    ('candySort', '🍬 Candy Sort'),
    ('spellDuel', '✨ Spell Duel'),
    ('mazeEscape', '🌀 Maze Escape'),
    ('trivia', '🧠 Trivia'),
    ('rhythm', '🎵 Rhythm'),
    ('voxelRun', '🧱 Voxel Run 3D'),
    ('graveyard3D', '🪦 Graveyard 3D'),
    ('abandonedMine', '🦇 Abandoned Mine'),
]